version: "3"
services:
  app:
    restart: always
    build: .
    command: uvicorn main:app --workers 2 --host=0.0.0.0 --port 8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file:
      - env/.env.prod
    networks:
      - web_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/etc/nginx/dist
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge


